#!/bin/bash

set -eu
set -o pipefail

SPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "$SPATH" ]; then SPATH="$PWD"; fi
SPATH="$(cd -P "$SPATH" && pwd)"

PRJ_ROOT_PATH="$SPATH/.."
PRJ_ROOT_PATH="$(cd "$PRJ_ROOT_PATH" && pwd)"

cd "$PRJ_ROOT_PATH" && echo cd $PWD

(cd "$PRJ_ROOT_PATH/.meta/bazel-rules-nodejs/scripts" && echo cd $PWD
 ./build_all.sh)
