#!/bin/bash

set -eu
set -o pipefail

SPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "$SPATH" ]; then SPATH="$PWD"; fi
SPATH="$(cd -P "$SPATH" && pwd)"

PRJ_ROOT_PATH="$SPATH/.."
PRJ_ROOT_PATH="$(cd "$PRJ_ROOT_PATH" && pwd)"

cd "$PRJ_ROOT_PATH" && echo cd $PWD

(cd "$PRJ_ROOT_PATH/.meta/bazel-rules-nodejs/scripts" && echo cd $PWD
 ./build_all.sh)

yarn remove @bazel/typescript
yarn add file:.meta/bazel-rules-nodejs/release/npm_bazel_typescript

# This is necessary to force Bazel to drop yarn_install cache
# for @bazel/typescript
bazel clean --expunge
